server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance_db?serverTimezone=Asia/Seoul
    username: root
    password: hgg1030028!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발: update / 배포: validate or none 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# JWT 관련 설정 (✅ 환경변수나 secrets 관리 필요)
jwt:
  secret: my-super-secret-key-that-is-very-long-1234567890  # 실제 배포 시 외부 환경변수로 분리 추천
  expiration: 86400000 # 24시간 (ms)

# CORS (선택) → SecurityConfig에서 처리 권장
# spring:
#   web:
#     cors:
#       allowed-origins: "*"
#       allowed-methods: "*"
#       allowed-headers: "*"